#!/usr/bin/env bash

SNAPSHOT=/daten/lokal/Programme/btrfs-snapshot-rotation/btrfs-snapshot
BASEDATA=/media/Daten/data
BASESNAPSHOT=/media/Daten/snap
#VOLUMES="host/*/* common/* user/*"
VOLUMES="host/*/* user/*"
