#!/usr/bin/env bash

SCRIPTNAME=`readlink -f $0`
DIR=`dirname $SCRIPTNAME`

# config for 'now'
SNAPNAME=daily
SNAPCOUNT=8

# read common config
source $DIR/snapshot-config

# execute snapshot
source $DIR/snapshot-do
